### PR TITLE
Try rendering report directly, without withr

### PR DESCRIPTION
**Pull request by Bisaloo**
This PR aims to understand better the requirement for withr, especially since it's presently failing CRAN checks

### CODE REVIEW

**Comment by Bisaloo** [comment]
@Karim-Mane, I cannot see any issues with this approach. Do you have more details why withr was necessary?

**Review by Karim-Mane — APPROVED** [review]

**Review by chartgerink — APPROVED** [review]

**Comment by Bisaloo** [comment]
@Karim-Mane, what is the status of https://github.com/epiverse-trace/cleanepi/pull/166 please? Did you find something that would block this PR?

**Comment by Karim-Mane** [comment]
> @Karim-Mane, I cannot see any issues with this approach. Do you have more details why withr was necessary?

`print_report()` was previously written in a way that the output HTML file is written in the user's current working directory by default (`output_directory = "."`). This was spotted, by @chartgerink, as a potential rejection factor during CRAN submission. The suggestion was to use {withr} to handle it.

**Comment by Karim-Mane** [comment]
> @Karim-Mane, what is the status of #166 please? Did you find something that would block this PR?

I am still trying to reproduce the error I was getting. There is no reason why this cannot be merged to the main branch so far.

If I am find anything from #166, I will raise it on that PR.

**Pull request merged**
